In [1]:
import pandas as pd
import numpy as np

In [2]:
dict1 = {
    "name":["Goku","Eren","Saitama"],
    "marks":[80,90,99]
    
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      name  marks
0     Goku     80
1     Eren     90
2  Saitama     99

In [5]:
df.to_csv('1.csv')

In [6]:
df.describe()

           marks
count   3.000000
mean   89.666667
std     9.504385
min    80.000000
25%    85.000000
50%    90.000000
75%    94.500000
max    99.000000

In [7]:
df.head(2)

   name  marks
0  Goku     80
1  Eren     90

In [8]:
df.tail(2)

      name  marks
1     Eren     90
2  Saitama     99

In [9]:
data = pd.read_csv('untitled.csv')

In [10]:
data

      Name  Marks
0     Musab    90
1  Abdullah    80
2    Ismail    70
3    israel    15
4       NaN

In [11]:
data['Marks']

0    90
1    80
2    70
3    15
4
Name: Marks, dtype: str

In [12]:
data['Marks'][1]

'80'

In [13]:
import pandas as pd

In [14]:
data = {
    "Name": ["Goku","Eren","Luffy","Kira","L"],
    "Marks": [95,91,89,98,99]
    
}

In [15]:
df = pd.DataFrame(data)

In [16]:
df

    Name  Marks
0   Goku     95
1   Eren     91
2  Luffy     89
3   Kira     98
4      L     99

In [17]:
df = pd.read_csv('1.csv')

In [18]:
df

   Unnamed: 0     name  marks
0           0     Goku     80
1           1     Eren     90
2           2  Saitama     99

In [19]:
df.head(1)

   Unnamed: 0  name  marks
0           0  Goku     80

In [20]:
df.tail(1)

   Unnamed: 0     name  marks
2           2  Saitama     99

In [21]:
dry_data = pd.read_csv('untitled.csv')
dry_data.dropna()

      Name  Marks
0     Musab    90
1  Abdullah    80
2    Ismail    70
3    israel    15

In [22]:
dry_data["Marks"]

0    90
1    80
2    70
3    15
4
Name: Marks, dtype: str

In [23]:
dry_data.index = ["a","b","c","d","e"]
dry_data

      Name  Marks
a     Musab    90
b  Abdullah    80
c    Ismail    70
d    israel    15
e       NaN

In [24]:
dry_data.index = ["first","second","third","fourth","fifth"]
dry_data

           Name  Marks
first      Musab    90
second  Abdullah    80
third     Ismail    70
fourth    israel    15
fifth        NaN

In [25]:
ser = pd.Series([np.random.rand(33)])
ser.tail()

0    [0.7119104269602308, 0.5538177611230245, 0.370...
dtype: object

In [26]:
newdf = pd.DataFrame(np.random.rand(334,4), index = np.arange(334))
newdf.head()

          0         1         2         3
0  0.357990  0.842495  0.884855  0.909746
1  0.124483  0.195010  0.099599  0.908668
2  0.886562  0.697395  0.685542  0.149772
3  0.792927  0.134184  0.422953  0.650547
4  0.332409  0.012045  0.323992  0.196489

In [27]:
type(newdf)

pandas.DataFrame

In [28]:
type(ser)

pandas.Series

In [29]:
newdf.describe()

                0           1           2           3
count  334.000000  334.000000  334.000000  334.000000
mean     0.488989    0.489971    0.486244    0.492973
std      0.283973    0.282263    0.302765    0.294131
min      0.004235    0.007614    0.001950    0.000250
25%      0.251584    0.253029    0.221247    0.249399
50%      0.489028    0.493229    0.471157    0.479251
75%      0.732999    0.717014    0.762590    0.753581
max      0.995663    0.991866    0.998333    0.989361

In [30]:

newdf.dtypes

0    float64
1    float64
2    float64
3    float64
dtype: object

In [31]:
newdf.head()

          0         1         2         3
0  0.357990  0.842495  0.884855  0.909746
1  0.124483  0.195010  0.099599  0.908668
2  0.886562  0.697395  0.685542  0.149772
3  0.792927  0.134184  0.422953  0.650547
4  0.332409  0.012045  0.323992  0.196489

In [32]:
newdf.to_numpy()

array([[0.3579898 , 0.84249536, 0.88485464, 0.90974628],
       [0.12448264, 0.19500972, 0.09959892, 0.90866761],
       [0.88656236, 0.69739461, 0.68554209, 0.14977167],
       ...,
       [0.06076701, 0.15603583, 0.74270088, 0.60228594],
       [0.62117428, 0.50297794, 0.25765563, 0.47754395],
       [0.91530222, 0.86822426, 0.20579193, 0.42948885]], shape=(334, 4))

In [33]:
newdf

            0         1         2         3
0    0.357990  0.842495  0.884855  0.909746
1    0.124483  0.195010  0.099599  0.908668
2    0.886562  0.697395  0.685542  0.149772
3    0.792927  0.134184  0.422953  0.650547
4    0.332409  0.012045  0.323992  0.196489
..        ...       ...       ...       ...
329  0.433994  0.348859  0.765011  0.922118
330  0.750024  0.213950  0.820845  0.077657
331  0.060767  0.156036  0.742701  0.602286
332  0.621174  0.502978  0.257656  0.477544
333  0.915302  0.868224  0.205792  0.429489

[334 rows x 4 columns]

In [34]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [35]:
newdf.columns

RangeIndex(start=0, stop=4, step=1)

In [36]:
# Transpose
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.357990,0.124483,0.886562,0.792927,0.332409,0.995663,0.056221,0.106484,0.948196,0.224094,...,0.188242,0.449599,0.478414,0.314409,0.207240,0.433994,0.750024,0.060767,0.621174,0.915302
1,0.842495,0.195010,0.697395,0.134184,0.012045,0.431803,0.454990,0.142847,0.266845,0.279371,...,0.471649,0.595134,0.403606,0.520581,0.632711,0.348859,0.213950,0.156036,0.502978,0.868224
2,0.884855,0.099599,0.685542,0.422953,0.323992,0.779375,0.911483,0.530051,0.072717,0.229006,...,0.127363,0.557159,0.238516,0.750181,0.471087,0.765011,0.820845,0.742701,0.257656,0.205792
3,0.909746,0.908668,0.149772,0.650547,0.196489,0.580867,0.815673,0.140909,0.390399,0.103346,...,0.136145,0.209078,0.265237,0.438942,0.849012,0.922118,0.077657,0.602286,0.477544,0.429489

In [37]:
# Axis=0 == Rows ans Axis=1 == Columns
# ascending = False is by-default True

newdf.sort_index(axis = 0 , ascending = False)

            0         1         2         3
333  0.915302  0.868224  0.205792  0.429489
332  0.621174  0.502978  0.257656  0.477544
331  0.060767  0.156036  0.742701  0.602286
330  0.750024  0.213950  0.820845  0.077657
329  0.433994  0.348859  0.765011  0.922118
..        ...       ...       ...       ...
4    0.332409  0.012045  0.323992  0.196489
3    0.792927  0.134184  0.422953  0.650547
2    0.886562  0.697395  0.685542  0.149772
1    0.124483  0.195010  0.099599  0.908668
0    0.357990  0.842495  0.884855  0.909746

[334 rows x 4 columns]

In [38]:
newdf.head()

          0         1         2         3
0  0.357990  0.842495  0.884855  0.909746
1  0.124483  0.195010  0.099599  0.908668
2  0.886562  0.697395  0.685542  0.149772
3  0.792927  0.134184  0.422953  0.650547
4  0.332409  0.012045  0.323992  0.196489

In [39]:
newdf[0]

0      0.357990
1      0.124483
2      0.886562
3      0.792927
4      0.332409
         ...
329    0.433994
330    0.750024
331    0.060767
332    0.621174
333    0.915302
Name: 0, Length: 334, dtype: float64

In [40]:
type(newdf[0])

pandas.Series

In [41]:
newdf.head(2)

          0         1         2         3
0  0.357990  0.842495  0.884855  0.909746
1  0.124483  0.195010  0.099599  0.908668

In [42]:
# change any rows and columns 
newdf.loc[0,0] = 654

In [43]:
newdf.head(2)

            0         1         2         3
0  654.000000  0.842495  0.884855  0.909746
1    0.124483  0.195010  0.099599  0.908668

In [44]:
newdf.columns = list("ABCD")

In [45]:
newdf.head()

            A         B         C         D
0  654.000000  0.842495  0.884855  0.909746
1    0.124483  0.195010  0.099599  0.908668
2    0.886562  0.697395  0.685542  0.149772
3    0.792927  0.134184  0.422953  0.650547
4    0.332409  0.012045  0.323992  0.196489

In [46]:
newdf.loc[0,0] = 654
newdf.head()

            A         B         C         D      0
0  654.000000  0.842495  0.884855  0.909746  654.0
1    0.124483  0.195010  0.099599  0.908668    NaN
2    0.886562  0.697395  0.685542  0.149772    NaN
3    0.792927  0.134184  0.422953  0.650547    NaN
4    0.332409  0.012045  0.323992  0.196489    NaN

In [47]:
# to remove some rows and columns
newdf = newdf.drop(0, axis = 1)

In [48]:
newdf.head()

            A         B         C         D
0  654.000000  0.842495  0.884855  0.909746
1    0.124483  0.195010  0.099599  0.908668
2    0.886562  0.697395  0.685542  0.149772
3    0.792927  0.134184  0.422953  0.650547
4    0.332409  0.012045  0.323992  0.196489

In [49]:
# to see only specific columns and rows
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.099599  0.908668
2  0.685542  0.149772

In [50]:
data = {
    "Name": ["A","B","C","D","E"],
    "Marks": [91,60,50,76,99]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     91
1    B     60
2    C     50
3    D     76
4    E     99

In [51]:
df.loc[df["Marks"]>90]

  Name  Marks
0    A     91
4    E     99

In [52]:
df

  Name  Marks
0    A     91
1    B     60
2    C     50
3    D     76
4    E     99

In [53]:
df.loc[4]

Name      E
Marks    99
Name: 4, dtype: object

In [54]:
dict1 = {
    "Name": ["A","B"],
    "Marks": [10,20]
    
}
df = pd.DataFrame(dict1)
df

  Name  Marks
0    A     10
1    B     20

In [55]:
df.describe()

           Marks
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [56]:
newdf.loc[[1,2],:]

          A         B         C         D
1  0.124483  0.195010  0.099599  0.908668
2  0.886562  0.697395  0.685542  0.149772

In [ ]:
newdf.head()

In [ ]:
newdf.loc[newdf[0]<0.5]

In [ ]:
# For .loc()  => name use krna h
# For .iloc()  => number use krna h 
newdf.iloc[0,2]

In [ ]:
newdf.head()

In [ ]:
newdf.iloc[[1,2],:]

In [ ]:
newdf.columns = list("ABCD")
newdf

In [ ]:
newdf.iloc[1,3]

In [ ]:
newdf.iloc[[1,332],:]

In [ ]:
newdf.iloc[[2,4],:]

In [ ]:
newdf.iloc[0,0] = 78
newdf

In [ ]:
newdf.iloc[[2,3],[1,3]]

In [ ]:
newdf.drop(['D'], axis = 1)

In [ ]:
newdf.drop(['B'],axis =1)

In [ ]:
newdf.head()

In [ ]:
newdf.drop([0,4], axis=0, inplace = True)

In [ ]:
newdf.head()

In [ ]:
# To reset the index(Rows)

newdf.reset_index(drop=True , inplace = True)

In [ ]:
newdf.head()

In [ ]:
# inplace=True means modify original Dataframe

In [ ]:
newdf.loc[:,0] = 0

In [ ]:
newdf.head().isnull()

In [ ]:
newdf.loc[:,0]

In [ ]:
newdf.columns = list("ABCD")
newdf.head()

In [ ]:
newdf.loc[:,['B']] = 56

In [ ]:
newdf.head(2)

In [ ]:
data = {
     "Name": ['A','B','C','D','E'],
     "Marks": [np.nan,pd.NaT,np.nan,pd.NaT,np.nan]
 }
df = pd.DataFrame(data)
df

In [ ]:
df.dropna(how ="all",axis=1)

In [ ]:
df.dropna()

In [ ]:
datas = {
     "Name": ['A','B','C','A','E'],
     "Marks": [70,80,50,60,90]
 }
cdf = pd.DataFrame(datas)
cdf

In [ ]:
cdf.drop_duplicates(subset='Name',keep="first")

In [ ]:
cdf.drop_duplicates(subset='Name',keep="last")

In [ ]:
cdf.drop_duplicates(subset='Name',keep=False)

In [ ]:
cdf.shape

In [ ]:
df.shape

In [ ]:
cdf.info()

In [ ]:
df.info()

In [ ]:
cdf['Name'].value_counts(dropna=False)

In [ ]:
# isnull() => null => True and False for not null
# notnull() => null => False and True for not null

cdf.notnull()

In [ ]:
# HomeWork
# create a dataframe in which contains only integers of 3 rows and 2 columns
# And apply following dataframe methods;
# df.describe(), df.mean(), df.min(), df.median(), df.std(), df.max(), df.count(), df.corr()

In [ ]:
df = pd.DataFrame(np.random.rand(3,2))
df.astype(int)

In [ ]:
data = {
    0 : [76,90,100],
    1: [89,56,91]
}

cdf = pd.DataFrame(data)
cdf

In [ ]:
cdf.describe()

In [ ]:
cdf.mean()

In [ ]:
cdf.corr()

In [ ]:
cdf.median()

In [ ]:
data = pd.read_excel('student_data.xlsx')

In [ ]:
data

In [ ]:
data.iloc[0,0] = 56

In [ ]:
data

In [ ]:
data.columns = ['Index', 'Name', 'Marks']

In [ ]:
data

In [ ]:
data.iloc[0,0] = 12

In [ ]:
data

In [ ]:
data.to_excel(

In [10]:
data = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Roll no": [7,5,np.nan,1,2],
    "Marks": [ 80, 70,np.nan,70,np.nan]
}

dfs = pd.DataFrame(data)
dfs

  Name  Roll no  Marks
0    A      7.0   80.0
1    B      5.0   70.0
2    C      NaN    NaN
3    D      1.0   70.0
4    E      2.0    NaN

In [12]:
data = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Marks": [ 85, 70,60,98,50]
}

dfs = pd.DataFrame(data)
dfs

  Name  Marks
0    A     85
1    B     70
2    C     60
3    D     98
4    E     50

In [2]:
data = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Marks": [ 85, 70,60,98,50]
}

dfs = pd.DataFrame(data)

In [4]:
data1 = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Roll no": [ 8, 7,6,9,5]
}

df = pd.DataFrame(data1)

In [19]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Ali", "John", "Sara"]
})

df2 = pd.DataFrame({
    "id": [2, 3, 4],
    "marks": [90, 78, 85]
})

In [22]:
# Inner merge: Keeps only common ids.
pd.merge(df1,df2, on="id", how="inner")

   id  name  marks
0   2  John     90
1   3  Sara     78

In [23]:
# Outer merge: Keeps everything from both.
pd.merge(df1,df2, on="id", how="outer")

   id  name  marks
0   1   Ali    NaN
1   2  John   90.0
2   3  Sara   78.0
3   4   NaN   85.0

In [24]:
# Right merge: Keeps all rows from left (df2).
pd.merge(df1,df2, on="id", how="right")

   id  name  marks
0   2  John     90
1   3  Sara     78
2   4   NaN     85

In [25]:
# Left merge: Keeps all rows from left (df1).
pd.merge(df1,df2, on="id", how="left")

   id  name  marks
0   1   Ali    NaN
1   2  John   90.0
2   3  Sara   78.0

In [2]:
data = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Marks": [ 85, 70,60,98,50]
}

dfs = pd.DataFrame(data)
dfs

  Name  Marks
0    A     85
1    B     70
2    C     60
3    D     98
4    E     50

In [4]:
data1 = {
    "Name": [ 'A', 'B', 'C', 'D', 'E'],
    "Roll no": [ 8, 7,6,9,5]
}

df = pd.DataFrame(data1)
df

  Name  Roll no
0    A        8
1    B        7
2    C        6
3    D        9
4    E        5

In [6]:
pd.merge(df,dfs, on="Name")

  Name  Roll no  Marks
0    A        8     85
1    B        7     70
2    C        6     60
3    D        9     98
4    E        5     50

In [4]:
# groupby()
import pandas as pd

Data = {
    "Name":['A','B','C','D','E'],
    "Department":['HR','IT','HR','IT','HR'],
    "Salary":[4000,5000,4500,5500,3500]
}
df = pd.DataFrame(Data)
df

  Name Department  Salary
0    A         HR    4000
1    B         IT    5000
2    C         HR    4500
3    D         IT    5500
4    E         HR    3500

In [8]:
# Sum:
df.groupby("Department")["Salary"].sum()

Department
HR    12000
IT    10500
Name: Salary, dtype: int64

In [22]:
# Group by one column:
df.groupby("Department")

In [10]:
# Mean or average salary per department:
df.groupby("Department")["Salary"].mean()

Department
HR    4000.0
IT    5250.0
Name: Salary, dtype: float64

In [11]:
# Count:
df.groupby("Department")["Salary"].count()

Department
HR    3
IT    2
Name: Salary, dtype: int64

In [15]:
# Max/Min:
max = df.groupby("Department")["Salary"].max()
min = df.groupby("Department")["Salary"].min()
print(max)
print(min)

Department
HR    4500
IT    5500
Name: Salary, dtype: int64
Department
HR    3500
IT    5000
Name: Salary, dtype: int64

In [24]:
# Multiple Aggregations:
df.groupby(["Department"])["Salary"].agg(["sum","min","mean","max","count"])

              sum   min    mean   max  count
Department
HR          12000  3500  4000.0  4500      3
IT          10500  5000  5250.0  5500      2

In [29]:
# Group by Multiple Columns:
df.groupby(["Department","Name"])["Salary"].count()

Department  Name
HR          A       1
            C       1
            E       1
IT          B       1
            D       1
Name: Salary, dtype: int64

In [64]:
# Real Life Example:

Data = {
    "Product":["Veg-Hakka-Noodles", "Egg-Roll","Chicken-Roll"],
    "Quantity":[2,4,3],
    "Price":[100,75,90],

}
df = pd.DataFrame(Data)
df["Total"] = df["Quantity"]*df["Price"]

print("-------------------Your Cart---------------------")
print(df)
print(" ")

print("-----------------Your Total Price----------------")
print("Total Price:",df["Total"].sum())
print(" ")

print("-------------🎉Thanks for coming🎉--------------")

-------------------Your Cart---------------------
             Product  Quantity  Price  Total
0  Veg-Hakka-Noodles         2    100    200
1           Egg-Roll         4     75    300
2       Chicken-Roll         3     90    270

-----------------Your Total Price----------------
Total Price: 770

-------------🎉Thanks for coming🎉--------------

In [2]:
Data = {
    "Product":["Foods", "Travel","Shopping", "Foods","Travel","Shopping"],
    "Price":[700,950,5000,800,1000,9000],

}
df = pd.DataFrame(Data)
df

    Product  Price
0     Foods    700
1    Travel    950
2  Shopping   5000
3     Foods    800
4    Travel   1000
5  Shopping   9000

In [14]:
orders = df.groupby("Product")["Price"].sum()
print(orders)
print("")
total = df["Price"].sum()
print("Total expenses this month: ",total)

Product
Foods        1500
Shopping    14000
Travel       1950
Name: Price, dtype: int64

Total expenses this month:  17450

In [12]:
data = {
    "Name":["Musab","Abdullah","Waris"],
    "Marks":[90,100,85]
}
df =pd.DataFrame(data)
df

       Name  Marks
0     Musab     90
1  Abdullah    100
2     Waris     85

In [13]:
# Sorting:(by values => sort_values()):
df.sort_values("Marks")

       Name  Marks
2     Waris     85
0     Musab     90
1  Abdullah    100

In [14]:
df.sort_values("Name")

       Name  Marks
1  Abdullah    100
0     Musab     90
2     Waris     85

In [15]:
# Descending order:
df.sort_values("Marks", ascending= False)

       Name  Marks
1  Abdullah    100
0     Musab     90
2     Waris     85

In [16]:
df.sort_values("Name", ascending= False)

       Name  Marks
2     Waris     85
0     Musab     90
1  Abdullah    100

In [17]:
# Sorting(by index => sort_index()):
df = pd.DataFrame(data, index = [2,0,1])
print(df)
print("")
print(df.sort_index())

       Name  Marks
2     Musab     90
0  Abdullah    100
1     Waris     85

       Name  Marks
0  Abdullah    100
1     Waris     85
2     Musab     90

In [20]:
# Sort by Multiple Columns:
df = pd.DataFrame(data, index = [0,1,2])
df.sort_values(["Marks","Name"])
# First sort by 'Marks' then by 'Name'..

       Name  Marks
2     Waris     85
0     Musab     90
1  Abdullah    100

In [4]:
# Pivot-Table:
data = {
    "Name":['A','B','A','D','B','D'],
    "Product":["Pen","Book","Book","Book","Pen","Pen"],
    "Sale":[100,200,300,150,400,500]
}
df = pd.DataFrame(data)
df

  Name Product  Sale
0    A     Pen   100
1    B    Book   200
2    A    Book   300
3    D    Book   150
4    B     Pen   400
5    D     Pen   500

In [5]:
df.pivot_table(
    values = "Sale",
    index = "Name",
    columns = "Product",
    aggfunc = "sum"
)

Product  Book  Pen
Name
A         300  100
B         200  400
D         150  500

In [13]:
data = {
    "Name":['A','B','A','B'],
    "Product":["Pen","Book","Book","Pen"],
    "Sale":[200,400,500,300]
}
df = pd.DataFrame(data)
df

  Name Product  Sale
0    A     Pen   200
1    B    Book   400
2    A    Book   500
3    B     Pen   300

In [18]:
df.pivot_table(
    values = "Sale",
    columns = "Product",
    index = "Name",
    aggfunc =("sum","count")
)

        count      sum
Product  Book Pen Book  Pen
Name
A           1   1  500  200
B           1   1  400  300